### 获取用户信息
POST http://localhost:8080/
Content-Type: application/json

{
  "service": "com.switchvov.magicrpc.demo.api.UserService",
  "methodSign": "findById@1_int",
  "args": [
    100
  ]
}

### 获取订单信息
POST http://localhost:8080/
Content-Type: application/json

{
  "service": "com.switchvov.magicrpc.demo.api.OrderService",
  "methodSign": "findById@1_java.lang.Integer",
  "args": [
    100
  ]
}
